// Shared enums for C&C CRM - matches Prisma schema

export enum UserRole {
  ADMIN = 'ADMIN',
  DISPATCHER = 'DISPATCHER',
  DRIVER = 'DRIVER',
  MOVER = 'MOVER',
  MANAGER = 'MANAGER',
  AUDITOR = 'AUDITOR'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED'
}

export enum JourneyStage {
  MORNING_PREP = 'MORNING_PREP',
  EN_ROUTE = 'EN_ROUTE',
  ONSITE = 'ONSITE',
  COMPLETED = 'COMPLETED',
  AUDITED = 'AUDITED'
}

export enum EntryType {
  PHOTO = 'PHOTO',
  NOTE = 'NOTE',
  GPS = 'GPS',
  SIGNATURE = 'SIGNATURE',
  CONFIRMATION = 'CONFIRMATION'
}

export enum MediaType {
  PHOTO = 'PHOTO',
  VIDEO = 'VIDEO',
  SIGNATURE = 'SIGNATURE'
}

export enum TagType {
  DAMAGE = 'DAMAGE',
  COMPLETED = 'COMPLETED',
  FEEDBACK = 'FEEDBACK',
  ERROR = 'ERROR',
  ISSUE = 'ISSUE'
}

// C&C Module flags for feature toggling
export enum CCModule {
  COMMAND_CONTROL = 'COMMAND_CONTROL',
  CONNECT_CONVERT = 'CONNECT_CONVERT',
  CREW_CUSTOMER = 'CREW_CUSTOMER',
  CAPTURE_CONFIRM = 'CAPTURE_CONFIRM',
  CALENDAR_CAPACITY = 'CALENDAR_CAPACITY',
  COST_COMPENSATION = 'COST_COMPENSATION',
  COMPLIANCE_CONSISTENCY = 'COMPLIANCE_CONSISTENCY',
  CHAT_COLLABORATION = 'CHAT_COLLABORATION',
  CASH_CONTRACTS = 'CASH_CONTRACTS',
  CLOUD_CONTROL = 'CLOUD_CONTROL',
  CLEAN_CONCISE = 'CLEAN_CONCISE',
  CUSTOMER_CARE = 'CUSTOMER_CARE'
} 