name: C&C CRM Automated Tests

on:
  # Run on schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'
  
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull requests
  pull_request:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test-services:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          # Install jq for JSON parsing
          sudo apt-get update
          sudo apt-get install -y jq curl
          
          # Install Node.js for React hydration tests
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install Puppeteer for browser testing
          npm install -g puppeteer
          
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v1.1.0 /usr/local/bin/render
          chmod +x /usr/local/bin/render
          
      - name: Make test script executable
        run: chmod +x scripts/automated-tests.sh
        
      - name: Run automated tests
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          ./scripts/automated-tests.sh --verbose --notify
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: |
            test-results-*.log
            test-report-*.md
          retention-days: 30
          
      - name: Comment on PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Find the latest test report
            const files = fs.readdirSync('.');
            const reportFiles = files.filter(f => f.startsWith('test-report-') && f.endsWith('.md'));
            
            if (reportFiles.length > 0) {
              const latestReport = reportFiles.sort().pop();
              const reportContent = fs.readFileSync(latestReport, 'utf8');
              
              const comment = `## 🤖 Automated Test Results
              
              ${reportContent}
              
              ---
              *This comment was automatically generated by the C&C CRM test suite.*`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
            
  notify-failures:
    needs: test-services
    if: failure() && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify on test failure
        run: |
          echo "Tests failed on scheduled run!"
          # Add your notification logic here:
          # - Slack webhook
          # - Email notification
          # - Discord webhook
          # - SMS notification
          
          # Example Slack notification:
          # curl -X POST -H 'Content-type: application/json' \
          #   --data '{"text":"🚨 C&C CRM automated tests failed! Check the logs for details."}' \
          #   ${{ secrets.SLACK_WEBHOOK_URL }} 